### PR TITLE
Dev

### PR DESCRIPTION
**Pull request by Jaya-Hoyt**
Heavily refactored routing to a make it more maintainable and readable.
* took out the redundant routes in web.php
    * route::resource handles all default crud routes
* removed /home route and put in the login successful popup into AuthenticatesUsers.php
    * I put it in the sendLoginResponse(Response $response) function
* refactored the logic in the Controllers' index functions to be show functions to be consistent with the framework
    * this also opens the door to using the index function as intended

### CODE REVIEW

**Review by jvachere — APPROVED** [review]
This looks great guys, you fixed a lot of things I did before I understood the framework 👍. This will make it much easier for Carl to maintain. The linking works well too.

**Comment by KyleCser** [comment]
Only thing I thought of is removing the link between the parent/child concepts. Did I overlook something or is that not possible?

**Review by KyleCser — APPROVED** [review]
Everything looks great. I kind of enjoy reading the code for this framework, it's pretty easy to follow and understand.

**Comment by Jaya-Hoyt** [comment]
I also added a delete link option for parent and child concepts. Give that a look, and @KyleCser can you style the delete button positioning if you don't like how it looks?

**Comment by KyleCser** [comment]
I'll change up the style later this evening most likely, if not then tomorrow. The bootstrap classes you're using aren't quite intended to be used that way.

I am also going to add in a "Are you sure" message when you delete the link. In CIS 376 it's suggested for good usability to have a confirmation for any destructive actions.

**Review by andrewtcobb — COMMENTED** [review]
More changes added to this pull request:
1. You can now view your account information by clicking the "Account Information" button from the drop down menu under your username in the top right corner.
2. You can update your account information by either clicking the "Edit Account Information" button from the drop down menu under your username or by clicking the edit button on the account information page.
3. If you try to change your email to an email which is already in the database, the website will not allow it and let you know what went wrong.
4. You can now permanently delete your account by clicking the "Deactivate Account" button on the account information page. This drops your column from the users table, so you have to make a whole new one from scratch if you sign up again.

-P.S. 
Some of the buttons are a little wonky, so if someone could adjust those that would be awesome.

**Pull request merged**
