### PR TITLE
U-Mich color scheme

### PR DESCRIPTION
**Pull request by KyleCser**
I've added UMich colors to the site. I've also added a UM-Deaborn logo to the navbar, we can take this out later if Carl doesn't approve but I thought it added some spice to the page. 

I also tweaked the process view page. I fixed a class and used some different tags to present the text better.

Let me know what you guys think!

### CODE REVIEW

**Comment by Jaya-Hoyt** [comment]
I like that you pulled some styles out of the HTML into a css file. We need to continue to do that until there are no more style blocks or inline styles directly in the HTML so we can control styles from css files only.

**Comment by KyleCser** [comment]
As pages become more polished and near complete we can strip out more css into individual files. It's a preference of mine to keep them isolated as to not clutter the page and html.

**Comment by Jaya-Hoyt** [comment]
The u of m logo at the top left that links back to the UMD website is confusing to me. Whenever I use a website, the logo on the top left always brings me back to the homepage of the web app I'm using.

**Comment by KyleCser** [comment]
yeah I forgot to switch that back to /home... will fix

**Review by Jaya-Hoyt — APPROVED** [review]
Pulled it to my machine and looks good.

**Review by jvachere — APPROVED** [review]
It looks great, good job.

**Pull request merged**
